name: dotnet publish

on:
  push:
    branches:
      - main
    paths:
      - Mellon/**
      - Mellon.Test/**
      - Mellon.IntegrationTest/**
      - mellon.sln
      - .github/workflows/*.yml

permissions: write-all

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --prune --unshallow
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Install git version
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.*
        dotnet-gitversion /updateprojectfiles
    - name: Build
      run: dotnet build -c release
    - name: Set integration test user secrets
      run: dotnet user-secrets set --project Mellon.IntegrationTest "TheOneApi:apiKey" "${{ secrets.ONE_API_KEY }}"
    - name: Test with the dotnet CLI
      run: dotnet test
    - name: Update project files in repo
      run: |
        git config --local user.email "jim.bennett@microsoft.com"
        git config --local user.name "JimBobBennett"
        git add ./**/*.csproj
        git commit -m "[skip actions] Update versions"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish package to NuGet
      run: dotnet nuget push ./Mellon/bin/Release/JimBobBennett.Mellon.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}